---
- name: 웹서버 설치
  hosts: all
  become: yes
  
  tasks:
    - name: httpd install
      yum:
        name: httpd
        state: present
    - name: index.html
      get_url:
        url: https://www.naver.com
        dest: /var/www/html
    - name: service 
      service:
        name: httpd
        state: started
        enabled: true
    - name: firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
